/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import javax.swing.Box;

/**
 *
 * @author ErickGuerron
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        BoxHorizontalGlue();
        setStyles();
    }

    public void BoxHorizontalGlue() {
        jbmBarraSuperior.remove(jmCuenta);
        jbmBarraSuperior.add(Box.createHorizontalGlue());
        jbmBarraSuperior.add(jmCuenta);

    }
    
        public void setStyles() {
        
        jdskPrincipal.setImagenFondo("/img/back.png");

        jbmBarraSuperior.setPreferredSize(new java.awt.Dimension(213, 40));
        jmAdministracion.setFont(new java.awt.Font("Segoe UI", 0, 18));
        jmiEstudiantes.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jmiCursos.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jmiInscripciones.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jmReportes.setFont(new java.awt.Font("Segoe UI", 0, 18));
        jmiMEstudiantes.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jmiMCursos.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jmiRInscripciones.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jmCuenta.setFont(new java.awt.Font("Segoe UI", 0, 18));
        jmiSalir.setFont(new java.awt.Font("Segoe UI", 0, 14));

    }

    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdskPrincipal = new componentes.JDKFondo();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jbmBarraSuperior = new javax.swing.JMenuBar();
        jmAdministracion = new javax.swing.JMenu();
        jmiEstudiantes = new javax.swing.JMenuItem();
        jmiCursos = new javax.swing.JMenuItem();
        jmiInscripciones = new javax.swing.JMenuItem();
        jmReportes = new javax.swing.JMenu();
        jmiMEstudiantes = new javax.swing.JMenuItem();
        jmiMCursos = new javax.swing.JMenuItem();
        jmiRInscripciones = new javax.swing.JMenuItem();
        jmCuenta = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gorro.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jdskPrincipal.add(jButton1);
        jButton1.setBounds(0, 0, 40, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/libro-cubierta-abierta.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jdskPrincipal.add(jButton2);
        jButton2.setBounds(40, 0, 40, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lapiz.png"))); // NOI18N
        jdskPrincipal.add(jButton3);
        jButton3.setBounds(80, 0, 40, 40);

        jbmBarraSuperior.setMinimumSize(new java.awt.Dimension(213, 500));

        jmAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/encuesta-cuadrada-vertical.png"))); // NOI18N
        jmAdministracion.setText("Administracion");
        jmAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAdministracionActionPerformed(evt);
            }
        });

        jmiEstudiantes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiEstudiantes.setText("Gestionar Estudiantes");
        jmiEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEstudiantesActionPerformed(evt);
            }
        });
        jmAdministracion.add(jmiEstudiantes);

        jmiCursos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiCursos.setText("Gestionar Cursos");
        jmiCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCursosActionPerformed(evt);
            }
        });
        jmAdministracion.add(jmiCursos);

        jmiInscripciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiInscripciones.setText("Inscripciones");
        jmAdministracion.add(jmiInscripciones);

        jbmBarraSuperior.add(jmAdministracion);

        jmReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prueba.png"))); // NOI18N
        jmReportes.setText("Reportes");

        jmiMEstudiantes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmiMEstudiantes.setText("Estudiantes");
        jmReportes.add(jmiMEstudiantes);

        jmiMCursos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmiMCursos.setText("Cursos");
        jmiMCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMCursosActionPerformed(evt);
            }
        });
        jmReportes.add(jmiMCursos);

        jmiRInscripciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmiRInscripciones.setText("Reporte Inscripciones");
        jmiRInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRInscripcionesActionPerformed(evt);
            }
        });
        jmReportes.add(jmiRInscripciones);

        jbmBarraSuperior.add(jmReportes);

        jmCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario-de-pizarra.png"))); // NOI18N
        jmCuenta.setText("Cuenta");

        jmiSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jmCuenta.add(jmiSalir);

        jbmBarraSuperior.add(jmCuenta);

        setJMenuBar(jbmBarraSuperior);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdskPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdskPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEstudiantesActionPerformed
        Alumnos a = new Alumnos();
        jdskPrincipal.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_jmiEstudiantesActionPerformed

    private void jmAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAdministracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmAdministracionActionPerformed

    private void jmiMCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMCursosActionPerformed

        
    }//GEN-LAST:event_jmiMCursosActionPerformed

    private void jmiRInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRInscripcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiRInscripcionesActionPerformed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCursosActionPerformed
       
        Cursos c = new Cursos();
        jdskPrincipal.add(c);
        c.setVisible(true);
    }//GEN-LAST:event_jmiCursosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Alumnos a = new Alumnos();
        jdskPrincipal.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Cursos c = new Cursos();
        jdskPrincipal.add(c);
        c.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenuBar jbmBarraSuperior;
    private componentes.JDKFondo jdskPrincipal;
    private javax.swing.JMenu jmAdministracion;
    private javax.swing.JMenu jmCuenta;
    private javax.swing.JMenu jmReportes;
    private javax.swing.JMenuItem jmiCursos;
    private javax.swing.JMenuItem jmiEstudiantes;
    private javax.swing.JMenuItem jmiInscripciones;
    private javax.swing.JMenuItem jmiMCursos;
    private javax.swing.JMenuItem jmiMEstudiantes;
    private javax.swing.JMenuItem jmiRInscripciones;
    private javax.swing.JMenuItem jmiSalir;
    // End of variables declaration//GEN-END:variables
}
