/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.awt.BorderLayout;
import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ACER
 */
public class ReporteCursoGeneros extends javax.swing.JInternalFrame {

    private JDesktopPane jdskPane; // referencia al DesktopPane del JFrame principal

    // Constructor por defecto (solo para pruebas o NetBeans)
    public ReporteCursoGeneros() {
        initComponents();
    }

    // Constructor que recibe el DesktopPane del formulario principal
    public ReporteCursoGeneros(JDesktopPane desktopPane) {
        initComponents();
        this.jdskPane = desktopPane;
        cargarReporte(desktopPane); // carga automática al abrir
    }

    private void cargarReporte(JDesktopPane desktopPane) {
        try {
            cuartouta.Conexion cc = new cuartouta.Conexion();
            Connection cn = cc.conectar();

            // Cargar el archivo .jasper
            InputStream reporteStream = getClass().getResourceAsStream("/reportes/reportCursoGeneros.jasper");
            if (reporteStream == null) {
                JOptionPane.showMessageDialog(this,
                        "No se encontró el archivo del reporte (reportCursoGenero.jasper)",
                        "Error", JOptionPane.ERROR_MESSAGE);
            return;
            }

            // Cargar imagen del encabezado
            InputStream imagenHeaderStream = getClass().getResourceAsStream("/img/HeaderReportes.png");
            if (imagenHeaderStream == null) {
                JOptionPane.showMessageDialog(this,
                        "No se encontró la imagen del encabezado (HeaderReportes.png)",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Parámetros del reporte
            Map<String, Object> parametros = new HashMap<>();
            parametros.put("IMAGEN_HEADER", imagenHeaderStream);

            // Cargar el reporte compilado
            JasperReport reporte = (JasperReport) JRLoader.loadObject(reporteStream);

            // Llenar el reporte
            JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);

            // Crear el visor embebido
            JRViewer visor = new JRViewer(imprimir);

            // Crear un InternalFrame para mostrar el reporte dentro del DesktopPane
            JInternalFrame frameReporte = new JInternalFrame("Reporte de Cursos por Género", true, true, true, true);
            frameReporte.setSize(desktopPane.getWidth(), desktopPane.getHeight());
            frameReporte.setLayout(new java.awt.BorderLayout());
            frameReporte.add(visor, java.awt.BorderLayout.CENTER);
            frameReporte.setVisible(true);
            // Agregar el frame al DesktopPane
            desktopPane.add(frameReporte);
            frameReporte.toFront();

            // Cerrar streams
            reporteStream.close();
            imagenHeaderStream.close();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error al generar el reporte: " + e.getMessage(),
                    "Error en el reporte",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteCursoGeneros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteCursoGeneros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteCursoGeneros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteCursoGeneros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteCursoGeneros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
