/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaces;

import cuartouta.Conexion;
import java.io.InputStream;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JInternalFrame;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import net.sf.jasperreports.engine.JRParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.util.SimpleFileResolver;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author THINKPAD
 */
public class ReporteXEstudiante extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReporteXEstudiante
     */
    public ReporteXEstudiante() {
        initComponents();
        jbtnReporte.setEnabled(false);
        configurarListenerCedula();
    }

    private void configurarListenerCedula() {
        jtxtCedula.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                validarCedula();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                validarCedula();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                validarCedula();
            }
        });
    }

    private void validarCedula() {
        String cedula = jtxtCedula.getText().trim();
        jbtnReporte.setEnabled(cedula.length() == 10);
    }

    public void generarReporte() {
        
        String cedula = jtxtCedula.getText().trim();

        if (cedula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese una cédula para la búsqueda.", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Connection conn = null;
        try {
            Conexion cn = new Conexion();
            conn = cn.conectar();

            if (conn == null) {
                JOptionPane.showMessageDialog(this, "No se pudo establecer conexión con la base de datos.", "Error de Conexión", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            InputStream jasperStream = getClass().getResourceAsStream("/reportes/EstudianteSeleccionado.jasper");
            if (jasperStream == null) {
                JOptionPane.showMessageDialog(this, "No se encontró el archivo del reporte (.jasper).", "Error de Archivo", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Map<String, Object> parametros = new HashMap<>();
            parametros.put(JRParameter.REPORT_FILE_RESOLVER, new SimpleFileResolver(new java.io.File("src/reportes/")));
            parametros.put("ID_ESTUDIANTE", cedula);

            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperStream, parametros, conn);

            if (jasperPrint.getPages().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontró ningún estudiante con la cédula proporcionada.", "Sin Resultados", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JInternalFrame reporteFrame = new JInternalFrame("Reporte de Estudiante", true, true, true, true);
                JRViewer viewer = new JRViewer(jasperPrint);

                reporteFrame.getContentPane().add(viewer);
                reporteFrame.pack();
                reporteFrame.setSize(800, 600);

                Principal.jdskPrincipal.add(reporteFrame);
                reporteFrame.setVisible(true);

                this.dispose(); 
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al generar el reporte.\n" + ex.getMessage(), "Error de JasperReports", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al cerrar la conexión a la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtCedula = new componentes.UTCcedula();
        jbtnReporte = new javax.swing.JButton();
        jbtnCerrar = new javax.swing.JButton();

        jLabel1.setText("Ingrese la cédula del estudiante:");

        jbtnReporte.setText("Generar reporte");
        jbtnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReporteActionPerformed(evt);
            }
        });

        jbtnCerrar.setText("Cerrar");
        jbtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jbtnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnReporte)
                    .addComponent(jbtnCerrar))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReporteActionPerformed
        generarReporte();
    }//GEN-LAST:event_jbtnReporteActionPerformed

    private void jbtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnCerrar;
    private javax.swing.JButton jbtnReporte;
    private componentes.UTCcedula jtxtCedula;
    // End of variables declaration//GEN-END:variables
}
